name: Deploy para Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SFTP para Hostinger
        uses: appleboy/scp-action@v0.1.7
        with:
          host:            ${{ secrets.FTP_SERVER }}
          username:        ${{ secrets.FTP_USERNAME }}
          password:        ${{ secrets.FTP_PASSWORD }}
          port:            ${{ secrets.SSH_PORT }}
          source:          "."
          target:          "public_html/pages"
          rm:              false
          overwrite:       true
          tar_dereference: true
